### PR TITLE
SD-1658 Don't parse past message bounds in invalid RFC3164

### PR DESCRIPTION
**Pull request by alanctgardner**
yolo++

### CODE REVIEW

**Comment by MarkRoddy** [comment]
Is this something we can test?

**Comment by MarkRoddy** [comment]
> yolo++

lolz

**Comment by alanctgardner** [comment]
I have a test as part of our syslog package, I'll add it to this package as well.

**Comment by MarkRoddy** [comment]
@alanctgardner test in our package is def more than enough for our release (see other comment)

**Pull request merged**
